---
# Home Assistant can get information from various devices. These can be used,
# for example, to track the location of your mobile phone.
#
# This configuration loads up my device trackers
#
# https://www.home-assistant.io/integrations/cast
#
cast: !include_dir_list ../entities/cast
