---
# I own a Nest thermostat, which does all my heating
#
# https://www.home-assistant.io/components/nest/
#
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  sensors:
    monitored_conditions:
      - temperature
      - target
      - humidity
      - operation_mode
