---
#
# The spotify integration allows control of spofity playback from HA
#
# https://www.home-assistant.io/integrations/spotify/
#

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret