---
# When it is end of work...
#
alias: '[lights] office_light_off'
trigger:
  platform: time
  at: '18:00:00'
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  - service: light.turn_off
    data:
      entity_id: light.office_light
