---
# When it is getting dark outside...
#
alias: '[lights] office_sunset'
trigger:
  platform: sun
  event: sunset
  offset: '-00:15:00'
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  - service: switch.turn_on
    data:
      entity_id: switch.office_light
      brightness_pct: 50
