---
header_text: '{{ time }}<br>{{ date }}'
menu: show
options: show
date_locale: en-GB
swipe: true
compact_mode: true
voice_hide: true
hide_help: true
hide_config: true
hide_unused: True
hide_refresh: true
