---
language: python
python:
  - "3.6"
jobs:
  include:
    - stage: yamllint
      name: "Checking YAML is Valid"
      install: pip install yamllint
      script: yamllint .
    - stage: remark-lint
      name: "Check Markdown"
      services: docker
      before_install:
        - docker pull pipelinecomponents/remark-lint:latest
      script:
        - remark --no-stdout --color --frail --use preset-lint-recommended .
    - stage: home-assistant-stable
      name: "Check against Home Assistant Stable"
      before_install:
        - mv ./.stubs/secrets.yaml ./config/secrets.yaml
        - touch ./config/home-assistant_v2.db
        - touch ./config/home-assistant.log
        - touch ./config/OZW_Log.txt
      install: pip3 install homeassistant
      script:
        - hass --version
        - hass --config ./config/ --script check_config --info all
