language: python
python:
  - "3.6"
before_install:
  - mv ./.stubs/secrets.yaml ./config/secrets.yaml
  - touch ./config/home-assistant_v2.db
  - touch ./config/home-assistant.log
  - touch ./config/OZW_Log.txt
install:
  - pip3 install homeassistant
script: make test
