---
# My living room light is connected using a shelly1 switch.
# This makes the device a "switch" withing Home Assistant and therefore
# it shows up as a switch in Google Assistant as well.
#
# This little light switch solves that issue.
#
# https://www.home-assistant.io/components/light.switch/
#
platform: switch
name: living_room_main_lights
entity_id: switch.living_room_main_lights
