---
# Set the default theme on start up of Home Assistant.
#
# This, of course, only affects machine that do not
# have a theme set.
#
alias: system_default_theme
trigger:
  platform: homeassistant
  event: start
action:
  service: frontend.set_theme
  data:
    name: discord
