---
# This alerts me on via Telegram when a new release
# of Home Assistant for Hass.io is released.
#
alias: '[system] system_upgrade_alert'
trigger:
  platform: state
  entity_id: sensor.version_available
condition:
  - condition: template
    value_template: >-
      {{
        states('sensor.version_available')
        !=
        states('sensor.version_current')
      }}
action:
  - service: telegram_bot.send_message
    data_template:
      title: Upgrade time!
      message: >-
        There is a Home Assistant upgrade for Hass.io pending!
        Version {{ states('sensor.version_available') }} just got released!
  - service: persistent_notification.create
    data_template:
      title: Upgrade time!
      message: >-
        There is a Home Assistant upgrade for Hass.io pending!
        Version {{ states('sensor.version_available') }} just got released!
        Rel Notes: https://www.home-assistant.io/latest-release-notes/
      notification_id: hassio_upgrade
