---
# The octoprint camera stream plugin.
#
# https://www.home-assistant.io/integrations/octoprint/
#
platform: mjpeg
name: OctoPrint
still_image_url: !secret octoprint_still_url
mjpeg_url: !secret octoprint_stream_url
