---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Home Control Panel
resources: !include_dir_list lovelace/resources
cch: !include lovelace/cards/compact_custom_header.yaml
views:
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/lights.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/security.yaml
  - !include lovelace/views/settings.yaml
  - !include lovelace/views/system.yaml
