---
path: lights
title: Lights
icon: mdi:lightbulb-on
cards:
  - type: horizontal-stack
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: Downstairs
            cards:
              - type: entities
                show_header_toggle: true
                entities:
                  - entity: switch.living_room_main_lights
                    name: Living room main lights
                    toggle: true
                    hide_when_off: false
              - type: light
                entity: light.living_room_lamp
                name: Living room lamp
                hide_when_off: false

      - type: vertical-stack
        cards:
          - type: horizontal-stack
            title: Upstairs
            cards:
              - type: entities
                show_header_toggle: false
                entities:
                  - entity: switch.office_light
                    name: Office light
                    toggle: true
                    hide_when_off: false
