---
path: lights
title: Lights
icon: mdi:lightbulb-on
cards:
  - type: vertival-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: entities
            title: Downstairs
            show_header_toggle: false
            entities:
              - entity: switch.living_room_main_lights
                name: Living Room Main Lights
                toggle: true
                hide_when_off: false
              - entity: light.living_room_lamp
                name: Living Room Lamp
                hide_when_off: false
          - type: entities
            title: upstairs
            show_header_toggle: false
            entities:
              - entity: switch.office_light
                name: Office Light
                toggle: true
                hide_when_off: false
