---
title: Info
icon: mdi:lan
path: info
panel: true
cards:
  - type: vertical-stack
    cards:
      - type: custom:layout-card
        layout: vertical
        cards:
          - type: vertical-stack
            cards:
              - type: picture-elements
                image: /local/lovelace/backgrounds/servers_background.jpg
                elements:
                  - type: custom:hui-glance-card
                    show_state: false
                    columns: 4
                    entities:
                      - sensor.server_proxy
                      - sensor.server_bastion
                      - sensor.storage_qnap
                    style:
                      left: 50%
                      top: 50%
                      width: 100%
                      --paper-card-background-color: rgba(0, 0, 0, 0.4)
                      --paper-item-icon-color: white
                      border-radius: 5px
                      color: rgb(0, 0, 0)
          - break
          - type: vertical-stack
            cards:
          - break
          - type: vertical-stack
            cards:
              - type: picture-elements
                image: /local/lovelace/backgrounds/network_background.jpg
                elements:
                  - type: custom:hui-glance-card
                    show_state: false
                    columns: 4
                    entities:
                      - sensor.juniper_ex2200
                    style:
                      left: 50%
                      top: 50%
                      width: 100%
                      --paper-card-background-color: rgba(0, 0, 0, 0.4)
                      --paper-item-icon-color: white
                      border-radius: 5px
                      color: rgb(0, 0, 0)
              - type: custom:mini-graph-card
                name: Speed test
                show:
                  icon: false
                  extrema: true
                  fill: false
                entities:
                  - sensor.speedtest_download
                  - sensor.speedtest_ping
                  - sensor.speedtest_upload
                line_color: "#389638"
