---
platform: template
sensors:
  octoprint_time_remaining_friendly:
    friendly_name: "Octoprint time remaining"
    value_template: >-
      {% set etime = states.sensor.octoprint_time_remaining.state | int %}
      {% set s = etime % 60 %}
      {% set m = ((etime % 3600) / 60) | int %}
      {% set h = ((etime % 86400) / 3600) | int %}
      {% set d = (etime / 86400) | int %}
      {%- if d > 0 -%}
        {%- if d == 1 -%}
          1 d
        {%- else -%}
          {{ days }} d
        {%- endif -%}
        {{ ', ' }}
      {%- endif -%}
      {%- if h > 0 -%}
        {%- if h == 1 -%}
          1 h
        {%- else -%}
          {{ h }} h
        {%- endif -%}
        {{ ', ' }}
      {%- endif -%}
      {%- if m > 0 -%}
        {%- if m == 1 -%}
          1 m
        {%- else -%}
          {{ m }} m
        {%- endif -%}
      {%- endif -%}
