---
platform: template
sensors:
  octoprint_time_elapsed_friendly:
    friendly_name: "Octoprint time elapsed"
    value_template: "{{ states('sensor.octoprint_time_elapsed') | int | timestamp_custom('%H:%M:%S', 0) }}"
