---
sensor:
  - platform: template
    sensors:
      battery_steve:
        value_template: '{{ states.device_tracker.life360_steve.attributes.battery|int }}'
        friendly_name: 'Steve Battery'
        unit_of_measurement: '%'
      battery_nicola:
        value_template: '{{ states.device_tracker.life360_nicola.attributes.battery|int }}'
        friendly_name: 'Nicola Battery'
        unit_of_measurement: '%'
proximity:
  home_steve:
    zone: home
    devices:
      - device_tracker.life360_steve
    tolerance: 20
    unit_of_measurement: mi
  home_nicola:
    zone: home
    devices:
      - device_tracker.life360_nicola
    tolerance: 20
    unit_of_measurement: mi
